# Generated by Django 3.0 on 2022-02-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cc', 'cc'), ('google pay', 'google pay'), ('apple pay', 'apple pay'), ('paypal', 'paypal')], max_length=50, verbose_name='payment method')),
                ('token', models.CharField(max_length=512, verbose_name='payment token')),
            ],
        ),
    ]
