# Generated by Django 3.1.14 on 2022-02-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('users', '0003_auto_20220202_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='addresses',
            field=models.ManyToManyField(blank=True, null=True, related_name='customer_addresses', to='users.address', verbose_name='customer addresses'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='payments',
            field=models.ManyToManyField(blank=True, null=True, related_name='payments', to='payment.method', verbose_name='payment methods'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.BigIntegerField(blank=True, help_text='customer phone number', null=True, verbose_name='customer phone number'),
        ),
    ]
