# Generated by Django 3.1.14 on 2022-02-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220202_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='customer_addresses', to='users.address', verbose_name='customer addresses'),
        ),
    ]
