# Generated by Django 3.1.14 on 2022-02-02 15:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220202_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('78c5c6f9-ddc3-40f5-87ef-2d618c97d894'), help_text='uuid field gives each customer a unique identifier', unique=True, verbose_name='uuid field'),
        ),
    ]
