# Generated by Django 3.1.14 on 2022-02-02 15:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customer_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_address',
            field=models.EmailField(blank=True, help_text='customer email address', max_length=254, null=True, verbose_name='customer email address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('84363b2a-f102-4532-b9e5-1928c7c0dd36'), help_text='uuid field gives each customer a unique identifier', unique=True, verbose_name='uuid field'),
        ),
    ]
