# Generated by Django 3.1.14 on 2022-02-05 19:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220202_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6b7afd0d-27b7-4ec9-8a14-7c739cdc1ca8'), help_text='uuid field gives each customer a unique identifier', unique=True, verbose_name='uuid field'),
        ),
    ]
