# Generated by Django 3.0 on 2022-02-02 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rating', '0001_initial'),
        ('users', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer', verbose_name='rating owner'),
        ),
        migrations.AddField(
            model_name='rating',
            name='customer_images',
            field=models.ManyToManyField(to='rating.image', verbose_name='customer images'),
        ),
        migrations.AddField(
            model_name='rating',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='rated product'),
        ),
    ]
