# Generated by Django 3.0 on 2022-02-02 13:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('a8e6b398-0a78-4443-b454-efc7d49e0e78'), help_text='uuid field gives each order a unique identifier', unique=True, verbose_name='uuid field')),
                ('placed_on', models.DateTimeField(auto_now_add=True, help_text='when this order was placed', verbose_name='placed on')),
                ('draft', models.BooleanField(default=False, verbose_name='order is a draft')),
                ('shippping', models.BooleanField(default=False, verbose_name='shipping')),
                ('amount_charged', models.BigIntegerField(help_text='amount for charged for order', verbose_name='amount charged')),
                ('pre_tax_amount', models.BigIntegerField(help_text='order total before tax', verbose_name='pre tax amount')),
                ('tax_amount', models.BigIntegerField(help_text='amount charged for taxes', verbose_name='taxes charged')),
                ('shipping_amount', models.BigIntegerField(help_text='amount charged for shipping', verbose_name='shipping charged')),
                ('gift', models.BooleanField(default=False, help_text='is this order a gift', verbose_name='gift')),
                ('gift_from', models.CharField(blank=True, help_text='who is this gift from', max_length=250, null=True, verbose_name='gift from')),
                ('gift_to', models.CharField(blank=True, help_text='who is this gift for', max_length=250, null=True, verbose_name='gift to')),
                ('gift_message', models.CharField(blank=True, help_text='message for gift', max_length=250, null=True, verbose_name='gift message')),
                ('status', models.CharField(choices=[('draft', 'draft'), ('paid', 'paid'), ('processing', 'processing'), ('shipped', 'shipped'), ('in transit', 'in transit'), ('delivered', 'delivered'), ('picked up', 'picked up'), ('error', 'error')], default='paid', max_length=50, verbose_name='order status')),
            ],
        ),
        migrations.CreateModel(
            name='wish_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='wish list', max_length=100, verbose_name='name')),
                ('get_notifications', models.BooleanField(default=False, verbose_name='get notifications')),
            ],
        ),
    ]
