# Generated by Django 3.0 on 2022-02-02 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discount', '0001_initial'),
        ('users', '0001_initial'),
        ('product', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish_list',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer', verbose_name='customer'),
        ),
        migrations.AddField(
            model_name='wish_list',
            name='products',
            field=models.ManyToManyField(to='product.configured_product'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupons_used',
            field=models.ManyToManyField(to='discount.coupon', verbose_name='coupons used on this order'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='customer who placed this order', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer', verbose_name='order cutomer'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='product.configured_product', verbose_name='products in order'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.address', verbose_name='shipping address'),
        ),
    ]
