# Generated by Django 3.1.14 on 2022-02-02 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220202_1443'),
        ('discount', '0002_auto_20220202_1438'),
        ('order', '0008_auto_20220202_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupons_used',
            field=models.ManyToManyField(blank=True, null=True, to='discount.coupon', verbose_name='coupons used on this order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pre_tax_amount',
            field=models.BigIntegerField(blank=True, help_text='order total before tax', null=True, verbose_name='pre tax amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_amount',
            field=models.BigIntegerField(default=0, help_text='amount charged for shipping', verbose_name='shipping charged'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_amount',
            field=models.BigIntegerField(default=0, help_text='amount charged for taxes', verbose_name='taxes charged'),
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('06f11e38-ed1a-4081-96a3-780edd06f6ca'), help_text='uuid field gives each order a unique identifier', unique=True, verbose_name='uuid field'),
        ),
        migrations.AlterField(
            model_name='wish_list',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='product.configured_product', verbose_name='products in wish list'),
        ),
    ]
