# Generated by Django 3.1.14 on 2022-02-02 14:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220202_1452'),
        ('discount', '0003_auto_20220202_1449'),
        ('order', '0012_auto_20220202_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupons_used',
            field=models.ManyToManyField(blank=True, to='discount.coupon', verbose_name='coupons used on this order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5034b538-5ea4-4349-9b3a-271cbfaa2f1b'), help_text='uuid field gives each order a unique identifier', unique=True, verbose_name='uuid field'),
        ),
        migrations.AlterField(
            model_name='wish_list',
            name='products',
            field=models.ManyToManyField(blank=True, to='product.configured_product', verbose_name='products in wish list'),
        ),
    ]
