# Generated by Django 3.1.14 on 2022-02-02 15:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20220202_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shippping',
            new_name='shipping',
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b3d2a6f8-dcfd-4e46-bbd1-7c1c71fcfe57'), help_text='uuid field gives each order a unique identifier', unique=True, verbose_name='uuid field'),
        ),
    ]
