# Generated by Django 3.1.14 on 2022-02-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='product price'),
        ),
        migrations.AlterField(
            model_name='product_option',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='if left empty price will be same as product', max_digits=10, verbose_name='option price'),
        ),
        migrations.AlterField(
            model_name='product_package',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='package price'),
        ),
    ]
