# Generated by Django 3.1.14 on 2022-02-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220202_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configured_product',
            name='amount',
            field=models.BigIntegerField(default=1, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='product description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='product-images/', verbose_name='main product image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(blank=True, null=True, to='product.product_option', verbose_name='product options'),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondary_images',
            field=models.ManyToManyField(blank=True, null=True, to='product.image', verbose_name='product secondary images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_description',
            field=models.TextField(blank=True, null=True, verbose_name='seo description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='seo name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='product.tag', verbose_name='product tags'),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='category description'),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='category-images', verbose_name='category image'),
        ),
        migrations.AlterField(
            model_name='product_option',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='product-images/options', verbose_name='main product image'),
        ),
        migrations.AlterField(
            model_name='product_option',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='if left empty price will be same as product', max_digits=10, null=True, verbose_name='option price'),
        ),
        migrations.AlterField(
            model_name='product_option',
            name='secondary_images',
            field=models.ManyToManyField(blank=True, null=True, to='product.image', verbose_name='product secondary images'),
        ),
        migrations.AlterField(
            model_name='product_package',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='product.product', verbose_name='package products'),
        ),
    ]
