# Generated by Django 3.1.14 on 2022-02-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220202_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(blank=True, to='product.product_option', verbose_name='product options'),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondary_images',
            field=models.ManyToManyField(blank=True, to='product.image', verbose_name='product secondary images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='product.tag', verbose_name='product tags'),
        ),
        migrations.AlterField(
            model_name='product_package',
            name='products',
            field=models.ManyToManyField(blank=True, to='product.product', verbose_name='package products'),
        ),
    ]
