# Generated by Django 3.1.14 on 2022-02-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220202_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_option',
            name='secondary_images',
            field=models.ManyToManyField(blank=True, to='product.image', verbose_name='product secondary images'),
        ),
    ]
