# Generated by Django 3.0 on 2022-02-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sale_pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name to identify in backend')),
                ('percent_off', models.IntegerField(blank=True, null=True, verbose_name='percent off')),
                ('sale_price', models.BigIntegerField(blank=True, null=True, verbose_name='sale price')),
                ('minimum_amount_of_products', models.IntegerField(blank=True, null=True, verbose_name='minimum amount of this product')),
                ('minimum_order_amount', models.BigIntegerField(blank=True, null=True, verbose_name='minimum order amount')),
                ('expires', models.DateTimeField(blank=True, null=True, verbose_name='sale expires')),
                ('uuid', models.UUIDField(verbose_name='product uuid')),
                ('products', models.ManyToManyField(to='product.product', verbose_name='product on sale')),
            ],
        ),
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name to identify in backend')),
                ('code', models.CharField(max_length=36, verbose_name='coupon code')),
                ('expires', models.DateTimeField(blank=True, null=True, verbose_name='coupon expiration date')),
                ('maximum_uses', models.BigIntegerField(blank=True, null=True, verbose_name='maximum allowed uses for this code')),
                ('per_user', models.IntegerField(blank=True, null=True, verbose_name='uses per customer')),
                ('uses', models.BigIntegerField(default=0, verbose_name='uses so far')),
                ('products', models.ManyToManyField(to='product.product', verbose_name='products for this coupon')),
            ],
        ),
    ]
