# Generated by Django 3.1.14 on 2022-02-02 14:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220202_1443'),
        ('discount', '0002_auto_20220202_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name to identify in backend'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='products',
            field=models.ManyToManyField(blank=True, to='product.product', verbose_name='products for this coupon'),
        ),
        migrations.AlterField(
            model_name='sale_pricing',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name to identify in backend'),
        ),
        migrations.AlterField(
            model_name='sale_pricing',
            name='products',
            field=models.ManyToManyField(blank=True, to='product.product', verbose_name='product on sale'),
        ),
        migrations.AlterField(
            model_name='sale_pricing',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='product uuid'),
        ),
    ]
